package taAllocation;

public class MutateThread extends Thread {

	private Facts facts;
	private Facts newFacts;
	/**
	 *  Constructor for mutate multi-thread  
	 * @param facts
	 * 				Takes in a fact to mutate.
	 * 
	 */
	public MutateThread(Facts facts) {
		this.facts = facts;
	}
	/**
	 *  Multi-thread run method 
	 */
	public void run() {
		try {
			newFacts = facts.mutate();
		} catch (InterruptedException e) {
			// do nothing
		}
	}
	/**
	 *  Method stops the mutating 
	 *  
	 */
	public void requestStop() {
		facts.stopMutate();
	}
	/**
	 *  Returns a new fact that was generated by run
	 * @return newFacts
	 */
	public Facts getNewFacts() {
		return newFacts;
	}

}
